### ISSUE TITLE
Cross-plataform?

### ISSUE THREAD

**Issue by pedrohoffmann** [Manuel83/craftbeerpi4#10]
Is the CBP4 will be cross-plataform? Like using others board, like orangepi? 
Is there any way that the missing sensors will be fixed or this is an hw problem?

**Comment by Manuel83** [comment]
CraftBeerPi 4 is able to run Cross Platform. Or other Systems like OrangePi some custom actor plugins needs to be developed. 

The plugin concepts supports this perfectly.

It seams that only a different lib should be use to control GPIO of orange pi.

https://pypi.org/project/OrangePi.GPIO/
pip install OrangePi.GPIO

Effort estimation 1-2h work
