### ISSUE TITLE
Temperature Sensor

### ISSUE THREAD

**Issue by Dirk23** [Manuel83/craftbeerpi4#108]
Hi,

I just installed craftbeerpi4 on my Raspberry Pi 3 B+. It was installed without any issues as as I could see. But sadly it doesn't show my Temperature Sensor. To wich pin on my Raspberry do I need to connect my Sensor?

Regards

Dirk

**Comment by avollkopf** [comment]
I can just refer to the documentation here: http://web.craftbeerpi.com/hardware/

or the discussion in the forum: https://www.facebook.com/groups/craftbeerpi

Not sure if you are using an extension board or if you are trying to connect the sensors directly to your Pi.  Disucssion in the user group will lead to better results

**Comment by Dirk23** [comment]
I have connected the Sensor as in the Diagram in the documentation, I have that resistor on a board with the sensor and connect directly to the Pins on the RPi. Everything is as in that documentation.

when i want to add that sensor, the Dropdown doesnt show any Device, only a "---"

i installed a fresh Bullseye on a SD Card and installed cbpi as in the documentation.

I don't have a Facebook Account and I don't want to sign up to Facebook.

**Comment by Dirk23** [comment]
An i'm a bit confused about that documentation. In your Picture, i can see the Temperature Sensors are connected to Pin7 wich is labeled  as "GPIO4".
![image](https://user-images.githubusercontent.com/4200682/210056565-32520637-946e-4b53-9c69-5e56fbdf53ed.png)

But on my RPi 3 B+ GPIO4 is on Pin16:
![image](https://user-images.githubusercontent.com/4200682/210056655-df1754f7-6125-44bf-93fc-ad7aca78bd9f.png)
And Pin7 is GPIO7 (GPCLK0) for me.

So where do i need to put that Sensor and SSR's now?

Can you please help me?

Regards

Dirk

**Comment by avollkopf** [comment]
I just know these ones: https://learn.sparkfun.com/tutorials/raspberry-gpio/gpio-pinout

As mentioned, a discussion is better in the forum. 

.. and the examples shoiwn on the web page is from Manuel.
