### ISSUE TITLE
Struggling to start writing a pluin with the parameters

### ISSUE THREAD

**Issue by avollkopf** [Manuel83/craftbeerpi4#11]
Hi, I was using the cbpi create plugin to start with a plugin.

The plugin is installed and I can also select this sensor in the hardware @ the web interface

Currently I am struggling with the parameters. I see and change them when adding the sensor.

However, in the code I just get 'None' when I try to get the individual props. I would love to port my current mod of the PT100&PT1000 plugin to CBPi4.

I am also not sure, if configuralbe = False has any effect like it had in CBPi3. If set to false, a avule can still be selected in the web interface

      @parameters([Property.Select(label="csPin", options=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27], description="GPIO Pin connected to the CS Pin of the MAX31865 - For MISO, MOSI, CLK no choice by default it's PIN 9, 10, 11"),
    Property.Select(label="ResSens", options = [100,1000],description = "Select 100 for PT100 or 1000 for PT1000"),
    Property.Number(label="RefRest", configurable = True, description = "Reference Resistor of the MAX31865 board (it's written on the resistor: 430 or 4300,....)"),
    Property.Number(label="offset", configurable = True, default_value = 0, description="Offset which is added to the received sensor data. Positive and negative values are both allowed."),
    Property.Number(label="ignore_below",configurable = True, default_value = 0, description="Readings below this value will be ignored"),
    Property.Number(label="ignore_above",configurable = True,default_value = 100, description="Readings above this value will be ignored"),
    Property.Select(label="ConfigTest", options=["[0xB2] - 3 Wires Manual","[0xD2] - 3 Wires Auto","[0xA2] - 2 or 4 Wires Manual","[0xC2] - 2 or 4 Wires Auto"], description="Choose beetween 2, 3 or 4 wire PT100 & the Conversion mode at 60 Hz beetween Manual or Continuous Auto")])

    class CustomSensor(CBPiSensor):

    def __init__(self, cbpi, id, props):
        super(CustomSensor, self).__init__(cbpi, id, props)
        self.value = 0
        self.misoPin = 9
        self.mosoPin = 10
        self.clkPin  = 11
        self.ResSens = self.props.get("ResSens")
        print(self.ResSens)

**Comment by Manuel83** [comment]
Hi 

can you please make sure to use the latest version.

I recommend to use vev see https://app.gitbook.com/@craftbeerpi/s/craftbeerpi4/development

To uninstall the current version.

`pip uninstall cbpi`

Reinstall

`pip install https://github.com/Manuel83/craftbeerpi4/archive/master.zip`

Check out GPIO Actor Example: https://github.com/Manuel83/craftbeerpi4/blob/master/cbpi/extension/gpioactor/__init__.py

**Comment by avollkopf** [comment]
Hi Manuel, did just a quick check this morning and installation of the latest GIT version seems to resolve the issue. However, Installation seems to require different rights and cbpi-ui is not starting (I installed it from within a venv):
```

 2021-02-03 05:50:17,154 - ERROR - cbpi.controller.plugin_controller - FAILED to load plugin cbpi4-ui
 2021-02-03 05:50:17,155 - ERROR - cbpi.controller.plugin_controller - No directory exists at '/usr/local/lib/python3.8/dist- packages/cbpi4-ui/build'
```
But the sensor data props seem to load now (see the log from the cbpi startup):
```

##### {'id': 'F5jRXZY2pRA9r9Aj58N9qX', 'name': 'My PT1000', 'props': {'ConfigTest': '[0xA2] - 2 or 4 Wires Manual', 'RefRest': '4300', 'ResSens': 1000, 'csPin': 6, 'ignore_above': '100', 'ignore_below': '0', 'offset': '0'}, 'state': {'value': 6}, 'type': 'PT100X_Sensor'}
1000

```

The last value 1000 is already retrieves via self.props.get.

So this seems to be resolved and I will install everything in a new container or venv to see if something went wrong in the existing container. 

From my point of view this issue can be closed.
