### ISSUE TITLE
Development: Contributing new sensors

### ISSUE THREAD

**Issue by nexysm** [Manuel83/craftbeerpi4#118]
Hello again guys,

I work in a company where we develop IoT communication module as well as sensors. Our sensors use single pair ethernet and they are really tiny. www.perinet.io

Oon the other hand I am a home brewer and wanted to try our sensors in the field. In order to do that I added new MQTT sensor and actor types. How can that be part of Cbpi4?

Best regards

**Comment by avollkopf** [comment]
Just write it as a plugin. Then everybody can install it if required -> https://openbrewing.gitbook.io/craftbeerpi4_support/readme/development/plugin_development

**Comment by nexysm** [comment]
@avollkopf thanks. I really enjoy developing this ...
