### ISSUE TITLE
No description shown in Hardware setup for Property.Select

### ISSUE THREAD

**Issue by avollkopf** [Manuel83/craftbeerpi4#14]
I noticed, that the description is not working for the Property.Select Parameter but for Property.Test and Property.Number

Same is true for the OneWire Sensor --> Interval

(Using latest GIThub version from Feb, 7, 2021)

![Screenshot 2021-02-07 121359](https://user-images.githubusercontent.com/43980694/107144848-33084180-693e-11eb-809e-0ca8a8f87784.png)

**Comment by Manuel83** [comment]
<img width="982" alt="Bildschirmfoto 2021-02-07 um 13 09 59" src="https://user-images.githubusercontent.com/5859486/107146025-d3159900-6945-11eb-9a8d-3552b3e2a682.png">

Fixed in the cbpi4ui 4.0.0.8 project
