### ISSUE TITLE
How to get the state of an actor?

### ISSUE THREAD

**Issue by avollkopf** [Manuel83/craftbeerpi4#23]
I want to get the state of an GPIOActor from a KettleLogic and try to use this command:

`self.pump=self.get_actor(self.agitator)`

where self.agitator is the id of my pump/actor.

Switching the pump on is working. However, the state is still 'False'

```
2021-02-14 12:36:46,563 - INFO - cbpi.extension.gpioactor - ACTOR UTN6oj6gDNrAZJyoKxCex9 ON - GPIO 18
{'id': 'UTN6oj6gDNrAZJyoKxCex9', 'name': 'Pump', 'props': {'GPIO': 18, 'Inverted': 'No'}, 'state': False, 'type': 'GPIOActor', 'instance': <cbpi.extension.gpioactor.GPIOActor object at 0xb1b58a90>}

```

Is there any other way to get the correct state ?

**Comment by Manuel83** [comment]
actor = self.get_actor_state("UTN6oj6gDNrAZJyoKxCex9")

See base.py line 42
https://github.com/Manuel83/craftbeerpi4/blob/93aea0c063435fa77fcd6fa4bcae9e3d9ec086e6/cbpi/api/base.py
