### ISSUE TITLE
Digits to be displayed for Sensors

### ISSUE THREAD

**Issue by avollkopf** [Manuel83/craftbeerpi4#24]
It's easy to implement this on the sensor side. The PT Sensor Plugin uses e.g. only two digits, while the onewire uses 3 digits. It's easy to add a parameter to the sensor and store only the desired digits. However, it would be probably better to store the full precission but display only the amount of digits in th UI that is selected as parameter for the particular sensor.

I was looking into cbpi4ui and found under util SensorValue.js which seems to be the correct place for this. I just failed to build a new ui with npm.... when I tried to change data to data.toFixed(1) for a test.

It would be great, if one can specify a digit parameter for each sensor where 2 is e.g. a default value. It has no effect on the stored data.

-> the 'digits' parameter for each sensor is used in the ui: e.g. data.toFixed(digits) is being displayed.

**Comment by Manuel83** [comment]
Well this need to be handled on server side. 
At client side I just want to display a value. A sensor value could also be a string. It depends on the implementation of the sensor.
