### ISSUE TITLE
Boil temperature with a system parameter

### ISSUE THREAD

**Issue by MarcioMonego** [Manuel83/craftbeerpi4#27]
Hello Manuel! Glad to see this great project reactivated.

Boil temperature is something that is some particular to some factors like brewing local altitude and brewer setup.
It will be good if it can be configured system wide and could be adjusted during boilstep without have to pause/resume to value take effect.

Thanks,

**Comment by Manuel83** [comment]
Hi 

this can be implemented by a boil step supporting "action" calls.
I just added this feature to the server part. I will add a button to the UI to call this action.
With an action you can update parameters at runtime for like in this example just start the timer directly.

See line 136
https://github.com/Manuel83/craftbeerpi4/blob/master/cbpi/extension/mashstep/__init__.py

Best regards
