### ISSUE TITLE
Still Getting config.json Error with Build 22

### ISSUE THREAD

**Issue by BrauereiAlt** [Manuel83/craftbeerpi4#28]
I am still running into the config.json error.  Error is occurring when trying to run cbpi setup.  For me this first occurred on my Mac when upgrading from b20 to b21.  Further upgrading to b22 has not resolved the issue.  Have done multiple uninstall then install/upgrade attempts, with and without sudo -H permissions. I thought my Mac python installation may have gone crossways, so I tried my Pi as well.  First confirmed on Pi I could setup/start b17, then upgraded to b22 with same issue.  Output below is from my Mac. Any thoughts on what I am missing?

Mac-mini:~ Kent$ sudo pip3 install --upgrade https://github.com/Manuel83/craftbeerpi4/archive/master.zip
WARNING: The directory '/Volumes/Kent's Mac mini External HD 1/Kent/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting https://github.com/Manuel83/craftbeerpi4/archive/master.zip
  Downloading https://github.com/Manuel83/craftbeerpi4/archive/master.zip
     - 4.2 MB 1.0 MB/s
Requirement already satisfied: aiohttp==3.7.3 in /usr/local/lib/python3.9/site-packages (from cbpi==4.0.0.22) (3.7.3)
Requirement already satisfied: aiohttp-auth==0.1.1 in /usr/local/lib/python3.9/site-packages (from cbpi==4.0.0.22) (0.1.1)
Requirement already satisfied: aiohttp-route-decorator==0.1.4 in /usr/local/lib/python3.9/site-packages (from cbpi==4.0.0.22) (0.1.4)
Requirement already satisfied: aiohttp-security==0.4.0 in /usr/local/lib/python3.9/site-packages (from cbpi==4.0.0.22) (0.4.0)
Requirement already satisfied: aiohttp-session==2.9.0 in /usr/local/lib/python3.9/site-packages (from cbpi==4.0.0.22) (2.9.0)
Requirement already satisfied: aiohttp-swagger==1.0.15 in /usr/local/lib/python3.9/site-packages (from cbpi==4.0.0.22) (1.0.15)
Requirement already satisfied: aiojobs==0.3.0 in /usr/local/lib/python3.9/site-packages (from cbpi==4.0.0.22) (0.3.0)
Requirement already satisfied: aiosqlite==0.16.0 in /usr/local/lib/python3.9/site-packages (from cbpi==4.0.0.22) (0.16.0)
Collecting cryptography==3.3.2
  Downloading cryptography-3.3.2-cp36-abi3-macosx_10_10_x86_64.whl (1.8 MB)
     |████████████████████████████████| 1.8 MB 3.6 MB/s 
Requirement already satisfied: requests==2.25.1 in /usr/local/lib/python3.9/site-packages (from cbpi==4.0.0.22) (2.25.1)
Requirement already satisfied: voluptuous==0.12.1 in /usr/local/lib/python3.9/site-packages (from cbpi==4.0.0.22) (0.12.1)
Requirement already satisfied: pyfiglet==0.8.post1 in /usr/local/lib/python3.9/site-packages (from cbpi==4.0.0.22) (0.8.post1)
Requirement already satisfied: pandas==1.1.5 in /usr/local/lib/python3.9/site-packages (from cbpi==4.0.0.22) (1.1.5)
Requirement already satisfied: click==7.1.2 in /usr/local/lib/python3.9/site-packages (from cbpi==4.0.0.22) (7.1.2)
Requirement already satisfied: shortuuid==1.0.1 in /usr/local/lib/python3.9/site-packages (from cbpi==4.0.0.22) (1.0.1)
Requirement already satisfied: tabulate==0.8.7 in /usr/local/lib/python3.9/site-packages (from cbpi==4.0.0.22) (0.8.7)
Requirement already satisfied: asyncio-mqtt in /usr/local/lib/python3.9/site-packages (from cbpi==4.0.0.22) (0.8.0)
Requirement already satisfied: cbpi4ui in /usr/local/lib/python3.9/site-packages (from cbpi==4.0.0.22) (0.0.9)
Requirement already satisfied: async-timeout<4.0,>=3.0 in /usr/local/lib/python3.9/site-packages (from aiohttp==3.7.3->cbpi==4.0.0.22) (3.0.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.9/site-packages (from aiohttp==3.7.3->cbpi==4.0.0.22) (5.1.0)
Requirement already satisfied: chardet<4.0,>=2.0 in /usr/local/lib/python3.9/site-packages (from aiohttp==3.7.3->cbpi==4.0.0.22) (3.0.4)
Requirement already satisfied: typing-extensions>=3.6.5 in /usr/local/lib/python3.9/site-packages (from aiohttp==3.7.3->cbpi==4.0.0.22) (3.7.4.3)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.9/site-packages (from aiohttp==3.7.3->cbpi==4.0.0.22) (1.6.3)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.9/site-packages (from aiohttp==3.7.3->cbpi==4.0.0.22) (20.3.0)
Requirement already satisfied: ticket-auth in /usr/local/lib/python3.9/site-packages (from aiohttp-auth==0.1.1->cbpi==4.0.0.22) (0.1.4)
Requirement already satisfied: jinja2~=2.11.2 in /usr/local/lib/python3.9/site-packages (from aiohttp-swagger==1.0.15->cbpi==4.0.0.22) (2.11.3)
Requirement already satisfied: pyYAML>=5.1 in /usr/local/lib/python3.9/site-packages (from aiohttp-swagger==1.0.15->cbpi==4.0.0.22) (5.4.1)
Requirement already satisfied: markupsafe~=1.1.1 in /usr/local/lib/python3.9/site-packages (from aiohttp-swagger==1.0.15->cbpi==4.0.0.22) (1.1.1)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.9/site-packages (from cryptography==3.3.2->cbpi==4.0.0.22) (1.14.5)
Requirement already satisfied: six>=1.4.1 in /usr/local/lib/python3.9/site-packages (from cryptography==3.3.2->cbpi==4.0.0.22) (1.15.0)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.9/site-packages (from pandas==1.1.5->cbpi==4.0.0.22) (2.8.1)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.9/site-packages (from pandas==1.1.5->cbpi==4.0.0.22) (1.20.1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.9/site-packages (from pandas==1.1.5->cbpi==4.0.0.22) (2021.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/site-packages (from requests==2.25.1->cbpi==4.0.0.22) (1.26.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/site-packages (from requests==2.25.1->cbpi==4.0.0.22) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.9/site-packages (from requests==2.25.1->cbpi==4.0.0.22) (2.10)
Requirement already satisfied: pycparser in /usr/local/lib/python3.9/site-packages (from cffi>=1.12->cryptography==3.3.2->cbpi==4.0.0.22) (2.20)
Requirement already satisfied: paho-mqtt>=1.5.0 in /usr/local/lib/python3.9/site-packages (from asyncio-mqtt->cbpi==4.0.0.22) (1.5.1)
Building wheels for collected packages: cbpi
  Building wheel for cbpi (setup.py) ... done
  Created wheel for cbpi: filename=cbpi-4.0.0.22-py3-none-any.whl size=4142205 sha256=dd5e361bba9957f46c8a435ba3f705595175e58b7f0ba95b894cacfdfbe80796
  Stored in directory: /private/tmp/pip-ephem-wheel-cache-fppxuw97/wheels/0b/60/9d/e5b514dbfd87632876113ae16876e6064c0745c55e8b8e3212
Successfully built cbpi
Installing collected packages: cryptography, cbpi
  Attempting uninstall: cryptography
    Found existing installation: cryptography 3.3.1
    Uninstalling cryptography-3.3.1:
      Successfully uninstalled cryptography-3.3.1
  Attempting uninstall: cbpi
    Found existing installation: cbpi 4.0.0.17
    Uninstalling cbpi-4.0.0.17:
      Successfully uninstalled cbpi-4.0.0.17
Successfully installed cbpi-4.0.0.22 cryptography-3.3.2

Mac-mini:~ Kent$ cbpi setup
Setting up CraftBeerPi
Folder created
Traceback (most recent call last):
  File "/usr/local/bin/cbpi", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cbpi/cli.py", line 229, in setup
    create_config_file()
  File "/usr/local/lib/python3.9/site-packages/cbpi/cli.py", line 51, in create_config_file
    shutil.copy(srcfile, destfile)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.9/site-packages/cbpi/config/config.json'

config directory:

Mac-mini:config Kent$ ls -l
total 40
-rw-r--r--  1 Kent  staff   31 Feb 17 21:22 actor.json
-rw-r--r--@ 1 Kent  staff  136 Feb 17 21:22 config.yaml
drwxr-xr-x  3 Kent  staff  102 Feb 17 21:22 dashboard
-rw-r--r--  1 Kent  staff   31 Feb 17 21:22 kettle.json
-rw-r--r--@ 1 Kent  staff   32 Feb 17 21:22 sensor.json
-rw-r--r--  1 Kent  staff   76 Feb 17 21:22 step_data.json

/usr/.../config directory:

Mac-mini:/ Kent$ cd /usr/local/lib/python3.9/site-packages/cbpi/config
Mac-mini:config Kent$ ls -l
total 4032
-rw-r--r--  1 root  admin       31 Feb 17 22:04 actor.json
-rw-r--r--  1 root  admin      136 Feb 17 22:04 config.yaml
-rw-r--r--  1 root  admin     1615 Feb 17 22:04 craftbeerpiboot
-rw-r--r--  1 root  admin     2595 Feb 17 22:04 create_database.sql
drwxr-xr-x  3 root  admin       96 Feb 17 22:04 dashboard
-rw-r--r--  1 root  admin       31 Feb 17 22:04 kettle.json
-rw-r--r--  1 root  admin       71 Feb 17 22:04 plugin_list.txt
-rw-r--r--  1 root  admin       32 Feb 17 22:04 sensor.json
-rw-r--r--  1 root  admin  2029331 Feb 17 22:04 splash.png
-rw-r--r--  1 root  admin       76 Feb 17 22:04 step_data.json

**Comment by BrauereiAlt** [comment]
Doesn't there need to be a config.json file in the package?

[https://github.com/Manuel83/craftbeerpi4/tree/master/cbpi/config](url)

**Comment by Biffe46** [comment]
Same, both in .21 and .22 as described above.

**Comment by JamFfm** [comment]
Same to me in .21 and .22. I  guess there is a missing config.json file in the repository like BrauereiAlt said.

**Comment by avollkopf** [comment]
As already mentioend, there seems to be a missing emtpy source config.json that should be copied from the static cbpi/config folder to the dynamic individual config folder during setup. This part of the cli.py script is looking for the source file:

```
   if os.path.exists(os.path.join(".", 'config', "config.json")) is False:
        srcfile = os.path.join(os.path.dirname(__file__), "config", "config.json")
        destfile = os.path.join(".", 'config')
        shutil.copy(srcfile, destfile)
```

**Comment by vojtech** [comment]
Already reported here https://github.com/Manuel83/craftbeerpi4/issues/26

**Comment by avollkopf** [comment]
@vojtech correct, but Manuel closed #26 and updates won't be distributed unless it will be re-opened. Since there is this issue, it should be ok.

The config/ points to Manuels local config where a config.json should be included. However, this will be his local config file.

**Comment by BrauereiAlt** [comment]
Already confirmed what Avollkopf indicated in his original ticket, if I add a dummy config.json file to the correct installation directory - I simply copied actor.json - then setup runs without error and successfully copies the file to my user/.../config directory.  But cbpi is looking for specific structure within that file and produces a runtime error.

If running correctly on Manuel’s systematic as he reported, should be a simple solution to include a proper initial skeletal file in the repository with the next build.  May need some additional initialization code if he manually configured his file.

**Comment by Manuel83** [comment]
Please make sure to run cbpi setup again

**Comment by avollkopf** [comment]
Just did that and I receive again this message after all the other:

```
(venv) pi@raspberrypi:~ $ cbpi setup
Setting up CraftBeerPi
Folder created
Traceback (most recent call last):
  File "/home/pi/venv/bin/cbpi", line 11, in <module>
    load_entry_point('cbpi', 'console_scripts', 'cbpi')()
  File "/home/pi/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/pi/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/craftbeerpi4/cbpi/cli.py", line 229, in setup
    create_config_file()
  File "/home/pi/craftbeerpi4/cbpi/cli.py", line 51, in create_config_file
    shutil.copy(srcfile, destfile)
  File "/usr/lib/python3.7/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/craftbeerpi4/cbpi/config/config.json'

```

Do you have an example of the config.json file that we could test. It's not created during setup and the script wants to copy it from '/home/pi/craftbeerpi4/cbpi/config/config.json' to /home/pi/config

**Comment by vhrdina-ford** [comment]
cbpi setup doesn't help, because config.json doesn't exist at /config/config.json

cli.py only copy existing file and there is no code to create it
if os.path.exists(os.path.join(".", 'config', "config.json")) is False:
        srcfile = os.path.join(os.path.dirname(__file__), "config", "config.json")
        destfile = os.path.join(".", 'config')
        shutil.copy(srcfile, destfile)

**Comment by vojtech** [comment]
cbpi setup doesn't help, because config.json doesn't exist at /config/config.json

cli.py only copy existing file and there is no code to create it
if os.path.exists(os.path.join(".", 'config', "config.json")) is False:
srcfile = os.path.join(os.path.dirname(file), "config", "config.json")
destfile = os.path.join(".", 'config')
shutil.copy(srcfile, destfile)

**Comment by Manuel83** [comment]
can you try build 23

**Comment by Biffe46** [comment]
sudo pip3 install https://github.com/Manuel83/craftbeerpi4/archive/master.zip
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://github.com/Manuel83/craftbeerpi4/archive/master.zip
  Downloading https://github.com/Manuel83/craftbeerpi4/archive/master.zip
     - 4.6MB 4.0MB/s
Requirement already satisfied: aiohttp-auth==0.1.1 in /usr/local/lib/python3.7/dist-packages (from cbpi==4.0.0.23) (0.1.1)
Requirement already satisfied: aiohttp-route-decorator==0.1.4 in /usr/local/lib/python3.7/dist-packages (from cbpi==4.0.0.23) (0.1.4)
Requirement already satisfied: aiohttp-security==0.4.0 in /usr/local/lib/python3.7/dist-packages (from cbpi==4.0.0.23) (0.4.0)
Requirement already satisfied: aiohttp-session==2.9.0 in /usr/local/lib/python3.7/dist-packages (from cbpi==4.0.0.23) (2.9.0)
Requirement already satisfied: aiohttp-swagger==1.0.15 in /usr/local/lib/python3.7/dist-packages (from cbpi==4.0.0.23) (1.0.15)
Requirement already satisfied: aiohttp==3.7.3 in /usr/local/lib/python3.7/dist-packages (from cbpi==4.0.0.23) (3.7.3)
Requirement already satisfied: aiojobs==0.3.0 in /usr/local/lib/python3.7/dist-packages (from cbpi==4.0.0.23) (0.3.0)
Requirement already satisfied: aiosqlite==0.16.0 in /usr/local/lib/python3.7/dist-packages (from cbpi==4.0.0.23) (0.16.0)
Requirement already satisfied: asyncio-mqtt in /usr/local/lib/python3.7/dist-packages (from cbpi==4.0.0.23) (0.8.0)
Requirement already satisfied: cbpi4ui in /usr/local/lib/python3.7/dist-packages (from cbpi==4.0.0.23) (0.0.9)
Requirement already satisfied: click==7.1.2 in /usr/local/lib/python3.7/dist-packages (from cbpi==4.0.0.23) (7.1.2)
Requirement already satisfied: cryptography==3.3.2 in /usr/local/lib/python3.7/dist-packages (from cbpi==4.0.0.23) (3.3.2)
Requirement already satisfied: pandas==1.1.5 in /usr/local/lib/python3.7/dist-packages (from cbpi==4.0.0.23) (1.1.5)
Requirement already satisfied: pyfiglet==0.8.post1 in /usr/local/lib/python3.7/dist-packages (from cbpi==4.0.0.23) (0.8.post1)
Requirement already satisfied: requests==2.25.1 in /usr/local/lib/python3.7/dist-packages (from cbpi==4.0.0.23) (2.25.1)
Requirement already satisfied: shortuuid==1.0.1 in /usr/local/lib/python3.7/dist-packages (from cbpi==4.0.0.23) (1.0.1)
Requirement already satisfied: tabulate==0.8.7 in /usr/local/lib/python3.7/dist-packages (from cbpi==4.0.0.23) (0.8.7)
Requirement already satisfied: voluptuous==0.12.1 in /usr/local/lib/python3.7/dist-packages (from cbpi==4.0.0.23) (0.12.1)
Requirement already satisfied: RPi.GPIO in /usr/local/lib/python3.7/dist-packages (from cbpi==4.0.0.23) (0.7.0)
Requirement already satisfied: ticket-auth in /usr/local/lib/python3.7/dist-packages (from aiohttp-auth==0.1.1->cbpi==4.0.0.23) (0.1.4)
Requirement already satisfied: markupsafe~=1.1.1 in /usr/local/lib/python3.7/dist-packages (from aiohttp-swagger==1.0.15->cbpi==4.0.0.23) (1.1.1)
Requirement already satisfied: jinja2~=2.11.2 in /usr/local/lib/python3.7/dist-packages (from aiohttp-swagger==1.0.15->cbpi==4.0.0.23) (2.11.3)
Requirement already satisfied: pyYAML>=5.1 in /usr/local/lib/python3.7/dist-packages (from aiohttp-swagger==1.0.15->cbpi==4.0.0.23) (5.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.7/dist-packages (from aiohttp==3.7.3->cbpi==4.0.0.23) (5.1.0)
Requirement already satisfied: async-timeout<4.0,>=3.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp==3.7.3->cbpi==4.0.0.23) (3.0.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp==3.7.3->cbpi==4.0.0.23) (20.3.0)
Requirement already satisfied: chardet<4.0,>=2.0 in /usr/lib/python3/dist-packages (from aiohttp==3.7.3->cbpi==4.0.0.23) (3.0.4)
Requirement already satisfied: typing-extensions>=3.6.5 in /usr/local/lib/python3.7/dist-packages (from aiohttp==3.7.3->cbpi==4.0.0.23) (3.7.4.3)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp==3.7.3->cbpi==4.0.0.23) (1.6.3)
Requirement already satisfied: paho-mqtt>=1.5.0 in /usr/local/lib/python3.7/dist-packages (from asyncio-mqtt->cbpi==4.0.0.23) (1.5.1)
Requirement already satisfied: six>=1.4.1 in /usr/lib/python3/dist-packages (from cryptography==3.3.2->cbpi==4.0.0.23) (1.12.0)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.7/dist-packages (from cryptography==3.3.2->cbpi==4.0.0.23) (1.14.4)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas==1.1.5->cbpi==4.0.0.23) (1.20.1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas==1.1.5->cbpi==4.0.0.23) (2021.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas==1.1.5->cbpi==4.0.0.23) (2.8.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests==2.25.1->cbpi==4.0.0.23) (2018.8.24)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests==2.25.1->cbpi==4.0.0.23) (2.6)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests==2.25.1->cbpi==4.0.0.23) (1.24.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi>=1.12->cryptography==3.3.2->cbpi==4.0.0.23) (2.20)
Building wheels for collected packages: cbpi
  Running setup.py bdist_wheel for cbpi ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-b4tio8wo/wheels/26/4f/cd/ca6f42a58fb79e10c7d6c167743906d325dddb7f567ffc9403
Successfully built cbpi
Installing collected packages: cbpi
  Found existing installation: cbpi 4.0.0.22
    Uninstalling cbpi-4.0.0.22:
      Successfully uninstalled cbpi-4.0.0.22
Successfully installed cbpi-4.0.0.23
pi@raspberrypi:~ $ cbpi setup
Setting up CraftBeerPi
Folder created
Config Folder created
pi@raspberrypi:~ $ cbpi start
START
2021-02-19 21:09:40,313 - INFO - cbpi.craftbeerpi - Init CraftBeerPI
2021-02-19 21:09:40,408 - INFO - cbpi.eventbus - Topic #
2021-02-19 21:09:40,653 - INFO - cbpi.craftbeerpi -
  _____            __ _   ____                 _____ _
 / ____|          / _| | |  _ \               |  __ (_)
| |     _ __ __ _| |_| |_| |_) | ___  ___ _ __| |__) |
| |    | '__/ _` |  _| __|  _ < / _ \/ _ \ '__|  ___/ |
| |____| | | (_| | | | |_| |_) |  __/  __/ |  | |   | |
 \_____|_|  \__,_|_|  \__|____/ \___|\___|_|  |_|   |_|


 _  _    ___   ___   ___  ____
| || |  / _ \ / _ \ |__ \|___ \
| || |_| | | | | | |   ) | __) |
|__   _| | | | | | |  / / |__ <
   | |_| |_| | |_| | / /_ ___) |
   |_(_)\___(_)___(_)____|____/



2021-02-19 21:09:40,653 - INFO - cbpi.craftbeerpi - www.CraftBeerPi.com
2021-02-19 21:09:40,653 - INFO - cbpi.craftbeerpi - (c) 2021 Manuel Fritsch
2021-02-19 21:09:40,655 - INFO - cbpi.controller.plugin_controller - Trying to load plugin gpioactor
2021-02-19 21:09:40,697 - INFO - cbpi.controller.plugin_controller - Trying to load plugin hysteresis
2021-02-19 21:09:40,701 - INFO - cbpi.controller.plugin_controller - Trying to load plugin mashstep
2021-02-19 21:09:40,705 - INFO - cbpi.controller.plugin_controller - Trying to load plugin dummysensor
2021-02-19 21:09:40,707 - INFO - cbpi.controller.plugin_controller - Trying to load plugin dummyactor
2021-02-19 21:09:40,710 - INFO - cbpi.controller.plugin_controller - Trying to load plugin mqtt
2021-02-19 21:09:40,712 - WARNING - cbpi.controller.plugin_controller - Plugin mqtt is not supporting version 4
2021-02-19 21:09:40,712 - INFO - cbpi.controller.plugin_controller - Trying to load plugin httpsensor
2021-02-19 21:09:40,718 - INFO - cbpi.controller.plugin_controller - Trying to load plugin onewire
2021-02-19 21:09:40,753 - INFO - cbpi.controller.plugin_controller - Try to load plugin:  cbpi4ui
2021-02-19 21:09:40,760 - INFO - cbpi.controller.plugin_controller - Plugin cbpi4ui loaded successfully
2021-02-19 21:09:40,760 - INFO - cbpi.controller.plugin_controller - Try to load plugin:  cbpi4-pt100x
2021-02-19 21:09:40,765 - INFO - cbpi.controller.plugin_controller - Plugin cbpi4-pt100x loaded successfully
2021-02-19 21:09:40,766 - INFO - root - SensorController Load
2021-02-19 21:09:40,767 - INFO - root - SensorController Starting
2021-02-19 21:09:40,767 - INFO - root - SensorController Start Id QZ28TDSp5ey2wuemP9nAhB
2021-02-19 21:09:40,768 - INFO - root - SensorController started QZ28TDSp5ey2wuemP9nAhB
2021-02-19 21:09:40,769 - INFO - root - SensorController Starting
2021-02-19 21:09:40,769 - INFO - root - SensorController Start Id TowgMULqaBj9iLPmQ5jo7V
2021-02-19 21:09:40,769 - INFO - root - SensorController started TowgMULqaBj9iLPmQ5jo7V
2021-02-19 21:09:40,769 - INFO - root - SensorController Starting
2021-02-19 21:09:40,770 - INFO - root - SensorController Start Id boJuATtoVvGbWofus6TusK
2021-02-19 21:09:40,770 - INFO - root - SensorController started boJuATtoVvGbWofus6TusK
2021-02-19 21:09:40,770 - INFO - root - SensorController Starting
2021-02-19 21:09:40,770 - INFO - root - SensorController Start Id SGsxcnpm4QhvaQT3RSsKQa
2021-02-19 21:09:40,770 - INFO - root - SensorController started SGsxcnpm4QhvaQT3RSsKQa
2021-02-19 21:09:40,771 - INFO - root - SensorController Starting
2021-02-19 21:09:40,771 - INFO - root - SensorController Start Id MNVtTna589QbpWpLFWiPu3
2021-02-19 21:09:40,772 - INFO - root - SensorController started MNVtTna589QbpWpLFWiPu3
2021-02-19 21:09:40,773 - INFO - root - INIT STEP Controller
2021-02-19 21:09:40,774 - INFO - root - ActorController Load
2021-02-19 21:09:40,775 - INFO - root - ActorController Starting
2021-02-19 21:09:40,775 - INFO - root - ActorController Start Id crp5TQivPACpwU6XWsWMqa
2021-02-19 21:09:40,776 - INFO - root - ActorController started crp5TQivPACpwU6XWsWMqa
2021-02-19 21:09:40,776 - ERROR - root - ActorController Cant start crp5TQivPACpwU6XWsWMqa - 'NoneType' object has no attribute 'get_state'
2021-02-19 21:09:40,776 - INFO - root - ActorController Starting
2021-02-19 21:09:40,776 - INFO - root - ActorController Start Id k2VroN6wtpceU6oghEQo6F
2021-02-19 21:09:40,777 - INFO - root - ActorController started k2VroN6wtpceU6oghEQo6F
2021-02-19 21:09:40,777 - ERROR - root - ActorController Cant start k2VroN6wtpceU6oghEQo6F - 'NoneType' object has no attribute 'get_state'
2021-02-19 21:09:40,777 - INFO - root - ActorController Starting
2021-02-19 21:09:40,777 - INFO - root - ActorController Start Id 5Zb8DCfP4Bfgp3WptebeD4
2021-02-19 21:09:40,777 - INFO - root - ActorController started 5Zb8DCfP4Bfgp3WptebeD4
2021-02-19 21:09:40,777 - ERROR - root - ActorController Cant start 5Zb8DCfP4Bfgp3WptebeD4 - 'NoneType' object has no attribute 'get_state'
2021-02-19 21:09:40,778 - INFO - root - ActorController Starting
2021-02-19 21:09:40,778 - INFO - root - ActorController Start Id L4FFuuzFH22BX59Cms8rrT
2021-02-19 21:09:40,778 - INFO - root - ActorController started L4FFuuzFH22BX59Cms8rrT
2021-02-19 21:09:40,778 - ERROR - root - ActorController Cant start L4FFuuzFH22BX59Cms8rrT - 'NoneType' object has no attribute 'get_state'
2021-02-19 21:09:40,778 - INFO - root - ActorController Starting
2021-02-19 21:09:40,778 - INFO - root - ActorController Start Id 2xakLrWydsuqSrjBhYszzM
2021-02-19 21:09:40,778 - INFO - root - ActorController started 2xakLrWydsuqSrjBhYszzM
2021-02-19 21:09:40,779 - INFO - root - KettleController Load
======== Running on http://0.0.0.0:8000 ========
(Press CTRL+C to quit)
2021-02-19 21:09:48,585 - INFO - aiohttp.access - 192.168.10.158 [19/Feb/2021:21:09:48 +0000] "GET / HTTP/1.1" 500 240 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
2021-02-19 21:09:49,502 - INFO - aiohttp.access - 192.168.10.158 [19/Feb/2021:21:09:49 +0000] "GET /favicon.ico HTTP/1.1" 500 198 "http://192.168.10.180:8000/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"

I get this msg from browser when trying to acess it. 

{"error": "'ConfigController' object has no attribute 'static'"}

Best regards

**Comment by Manuel83** [comment]
Can you run 

`pip list 
`
and show me your installed versions

**Comment by Biffe46** [comment]
pi@raspberrypi:~ $ pip3 list
Package                 Version
----------------------- ---------
aiohttp                 3.7.3
aiohttp-auth            0.1.1
aiohttp-route-decorator 0.1.4
aiohttp-security        0.4.0
aiohttp-session         2.9.0
aiohttp-swagger         1.0.15
aiojobs                 0.3.0
aiosqlite               0.16.0
asn1crypto              0.24.0
async-timeout           3.0.1
asyncio-mqtt            0.8.0
attrs                   20.3.0
cbpi                    4.0.0.23
cbpi4-pt100x            0.0.2
cbpi4ui                 0.0.9
certifi                 2018.8.24
cffi                    1.14.4
chardet                 3.0.4
click                   7.1.2
cryptography            3.3.2
entrypoints             0.3
idna                    2.6
Jinja2                  2.11.3
keyring                 17.1.1
keyrings.alt            3.1.1
MarkupSafe              1.1.1
multidict               5.1.0
numpy                   1.20.1
paho-mqtt               1.5.1
pandas                  1.1.5
pip                     18.1
pycparser               2.20
pycrypto                2.6.1
pyfiglet                0.8.post1
PyGObject               3.30.4
python-apt              1.8.4.3
python-dateutil         2.8.1
pytz                    2021.1
pyxdg                   0.25
PyYAML                  5.4.1
requests                2.25.1
RPi.GPIO                0.7.0
SecretStorage           2.3.1
setuptools              40.8.0
shortuuid               1.0.1
six                     1.12.0
ssh-import-id           5.7
tabulate                0.8.7
ticket-auth             0.1.4
typing-extensions       3.7.4.3
urllib3                 1.24.1
voluptuous              0.12.1
wheel                   0.32.3
yarl                    1.6.3

**Comment by Manuel83** [comment]
I could reproduce and fixed it.
The issue was the refactoring of the config controller.

Can you try again please

**Comment by Biffe46** [comment]
Working, great work!

**Comment by Biffe46** [comment]
PT100 sensors are not working atm, one wire are, ill try to intall Alexanders addon again to see if its fixed

**Comment by avollkopf** [comment]
> 
> 
> PT100 sensors are not working atm, one wire are. Ill try to reintall Alexanders addon to see if its fixed.
> 
> **update**
> Reinstalled and re added it to the cbpi even tho it allready was loaded correctly with no luck.
> 
> plugin: cbpi4-pt100x
> 2021-02-19 21:32:00,147 - INFO - cbpi.controller.plugin_controller - Plugin cbpi 4-pt100x loaded successfully

Only a minor chage requied in the pt100x plugin. Will update it today.

**Comment by Biffe46** [comment]
Thank you Alexander. Ill give it a try later today.
