### ISSUE TITLE
Sensor logs store in logs but nor in logs/sensors -> issue or not?

### ISSUE THREAD

**Issue by avollkopf** [Manuel83/craftbeerpi4#31]
Not sure if this is an issue or not.

PT100X  is also working with a small change. I also added the log function and will publish an update later today

I have one OneWie and on PT1000 and logs are stored in logs but nor in the subdirectory sensors:

```
(venv) pi@raspberrypi:~ $ cd logs/
(venv) pi@raspberrypi:~/logs $ ll
insgesamt 80
drwxr-xr-x  3 pi pi  4096 Feb 20 07:49 .
drwxr-xr-x 14 pi pi  4096 Feb 20 07:55 ..
-rw-r--r--  1 pi pi 36948 Feb 20 09:43 sensor_BoNuRALLddVwrouDooaSNE.log
-rw-r--r--  1 pi pi 18995 Feb 20 09:43 sensor_kDuEmKoDLtcnicGwYpjvZD.log
drwxr-xr-x  2 pi pi  4096 Feb 19 06:49 sensors
```

Is this on purpose or should the sensor logs be stores in the sensor subdirectory?

**Comment by Manuel83** [comment]
At the moment this is ok. Next week I'm working on the log data to integrate this into the UI. Then I need to sort this.
