### ISSUE TITLE
Functionality of timer

### ISSUE THREAD

**Issue by avollkopf** [Manuel83/craftbeerpi4#34]
Currently , the step starts the timer under these conditions:

MashSteps:
```
    async def run(self):
        while True:
            await asyncio.sleep(1)
            sensor_value = self.get_sensor_value(self.props.Sensor)
            if sensor_value is not None and sensor_value.get("value") >= int(self.props.Temp) and self.timer == None:
                self.timer.start()
```
However, self.timer reamins None and the timer won't start.

Changing the last condition to 'self.timer._task == None' would be working.

There i also the question on how steps can get the remaining time of the timer (e.g. for hop alarms).

in the Timer an additional variable would be working 

Under __init__:
self.remaining_time = None

and then in the _job:

```
    async def _job(self):
        self.start_time = time.time()
        self.count = int(round(self._timemout, 0))
        try:
            for seconds in range(self.count, 0, -1):
                if self._update is not None:
                    await self._update(self,seconds)
                self.remaining_time = seconds
                await asyncio.sleep(1)
```

Other routines like steps could acces the remaining time via self.timer.remaining_time.

Currently all other variable seem to remain at the initial specified target timeout for the step. 

But maybe I am missing something else.

**Comment by BrauereiAlt** [comment]
I think self.timer remaining none may be related to the target temp not get passed correctly from the mash step controller to the kettle controller.  At least my target temp displayed in the dashboard does not change based on values configured in the mash steps.  The displayed value changes only in response to changes to the hardware setup parameter or using the dashboard kettle control tool.

I also think sensor values are no longer be handled correctly, at least not for dummy sensors.  The code to randomize the value of dummy sensors is no longer triggered. I was able to force a dummy sensor value through changing the initial value in code and that was reflected in the dashboard, but the step timer still did not activate.

**Comment by avollkopf** [comment]
I changed some code in the steps and the target temp is being trasfered. However, you need to push F5 for an update in the browser. await self.push_update() does not seem to help. But let's wait for the next update. I assume plenty of changes have been made

**Comment by avollkopf** [comment]
.. and you are right. I was wrong with my initial description. Self.timer is not none from the beginning. Once the timer is being created during start, it becomes not none. Therefore, the timer is never started automatically. This condition should be asking, if a timer job is running. If not. The timer has to be started if the other temp condition is fulfilled. In this case a timer task is being created and not none anymore. This prevents the step from starting the timer again.

**Comment by Prash3r** [comment]
i tried to pull from you @avollkopf it successfully repaired the `cbpi create` command but i was still not able to get data out of a sensor; value was stuck on `---` and refreshing didnt help (MyCustomSensor with no alteration apart from uncommenting the setup registration). Debugging revealed that neither the `__init__()` of my class nor the run was being called. This is too deep for me. Without any changes to my code everything was fine (`cbpi create` still broken) after i installed version 4.0.0.16 via `pip install -Iv cbpi==4.0.0.16` after `pip uninstall cbpi` in my virtual env.

so for everyone wanting to get a head start on plugin creation i suggest pulling the version 16 and when seeing the `cbpi create` error to replace `{{ name }}` with `yourPluginName` in the config.yaml in your plugin folder. then proceeding normally.

**Comment by avollkopf** [comment]
@Prash3r what sensor are you using? My PT1000 is working with my plugin and the onewires are also working.

The dummy sensor has an issue with the latest version due to changes in the sensor controller

`while self.running is True:`

needs to be replace with:

`while True:`

But this is not really related to this paticular issue.

**Comment by Prash3r** [comment]
hmm i see. The automatically generated Sensor `MyCustomSensor` when creating a plugin is very similar to the DummySensor and also uses `while self.running is True:` thats where i started to try and create a sensor myself. thank you for your quick reply - i think i can go back to your current version now.

**Comment by avollkopf** [comment]
Found one way to get the remaining seconds in the mash steps. 

self.summary returns a string with this format '00:00:00'

The following function in a step converts it to seconds which can be used for hop alarms
```
    async def get_remaining_time(self):
        if self.timer.start_time != None:
            ftr = [3600,60,1]
            self.remaining_time = sum([a*b for a,b in zip(ftr, map(int,self.summary.split(':')))])
        else:
            self.remaining_time = None
        return self.remaining_time
```

Now I have only one more question. How to add 5 Minutes to a running timer? I am struggling to add time to a running timer job/task while the for loop is active. Changing self.count does not help.

**Comment by Manuel83** [comment]
To get the remaining seconds just provide an on_update callback to the timer.
This is called every second.

To call some code if the timer is elapsed add the on_done callback

You can start multiple timers. Just create several timer objects and start them.

```
 async def on_timer_done(self,timer):
        self.summary = ""
        await self.next()

async def on_timer_update(self,timer, seconds):
        self.summary = Timer.format_time(seconds)
        await self.push_update()
        
        
self.timer = Timer(int(self.props.Timer) *60 ,on_update=self.on_timer_update, on_done=self.on_timer_done)
```

**Comment by avollkopf** [comment]
@Manuel83  Thanks, It can be that easy. I was basically using that routine, but the self.summary and calculated back the seconds... as self.summary returns the format '00:00:00'

I changed the routine in my step to:

```
async def on_timer_update(self,timer, seconds):
        self.summary = Timer.format_time(seconds)
        self.remaining_seconds = seconds
        await self.push_update()
```

and use now self.remaining_seconds as int to check for the hop alarms.

The other question was more on an existing/running timer. Is it possible to add e.g. 5 minutes to a running timer?

Lots of questions...

Throughout the week, I will provide a couple of steps as plugin

**Comment by Manuel83** [comment]
I added an `add` to the Timer object

t = Timer(60, .....)

# add 40 seconds
await t.add(40)

https://github.com/Manuel83/craftbeerpi4/blob/master/cbpi/api/timer.py

Can you try it out please

**Comment by avollkopf** [comment]
Sounds great. Will try that tonight. I just updated my steps plugin with basically all steps required to run a Braumeister. Will try that out and report back tonight.

**Comment by avollkopf** [comment]
@Manuel83 Works like a treat :-) Thanks.

From my side we could close this issue.
