### ISSUE TITLE
When installing i get the following error : 

### ISSUE THREAD

**Issue by vaughnlfisher** [Manuel83/craftbeerpi4#36]
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-sBdu2h/aiohttp-route-decorator/setup.py", line 13, in <module>
        long_description=open('README.rst', encoding='utf-8').read(),
    TypeError: 'encoding' is an invalid keyword argument for this function

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-sBdu2h/aiohttp-route-decorator/

**Comment by Prash3r** [comment]
wild guess: you are probably using python 2.x and should use python 3.x (im running Python 3.9.2).

run `python --version` to find out which version is installed as the default on your machine.

This is a python 3 project. ty running the setup with the `python3` command

**Comment by vaughnlfisher** [comment]
That fixed it a treat - thanks.
On another note is their plans to port across the existing plugins?
