### ISSUE TITLE
Maintainer proposal

### ISSUE THREAD

**Issue by staticdev** [Manuel83/craftbeerpi4#4]
@Manuel83 I am a python professional for more than 10 years, CBP user and fan. If you grant me maintainer role in craftbeerpi3 repositort, I will do my best to solve the issues, PRs and keep alive this wonderful project. You can direct contact me by mail on thiagocavila at gmail.

**Comment by gabrielclimb** [comment]
@staticdev, I think it's better fork. If want help with project let me know
