### ISSUE TITLE
craftbeerpi4-ui is not updated during installation

### ISSUE THREAD

**Issue by JamFfm** [Manuel83/craftbeerpi4#40]
I did the update via 
sudo pip3 install https://github.com/Manuel83/craftbeerpi4/archive/master.zip
Server update of version 27 works fine but UI is not updated. It remais at version 009.
Therefore cbpi 4 with update 27 looks the same as  version 17 and recepie does not work.
Copying the content of the repository craftbeerpi4-ui to /usr/local/lib/python3.7/dist-packages/cbpi4ui did work. 
Pip3 list still shows 009 and not 012 version.

Please integrate UI Version 012 in the setup so there is a proper install of the UI.

Thanks for beeing back again and your work!!

**Comment by BrauereiAlt** [comment]
I too had to manually install the updated UI.  Did so as shown below and pip list shows the correct 0.0.12 version.

sudo python3 -m pip install --upgrade https://github.com/Manuel83/craftbeerpi4-ui/archive/main.zip

**Comment by Manuel83** [comment]
I uploaded a new version to pypi

Solution is to uninstall the UI
`sudo python3 -m pip uninstall cbpi4ui `
`sudo python3 -m pip install  cbpi4ui`

Let me know if I can close the issue

**Comment by BrauereiAlt** [comment]
Manuel, do you need to specify a UI Version in the dependency list to force an update when necessary?

**Comment by mmillerbr** [comment]
Uninstalling and reinstalling using the commands above solves the issue.
```
cbpi                    4.0.0.29
cbpi4ui                 0.0.13
```
Now I can see the new dashboard with the new icons, as well as the Mash Profile option, that was not working for me.
Good job Manuel !

**Comment by JamFfm** [comment]
Now setup works. Did a new install and got 4.0..0.29 and 0.0.13 for UI.
