### ISSUE TITLE
saving sensor hardware setup doesnt kill orphan run() loops

### ISSUE THREAD

**Issue by Prash3r** [Manuel83/craftbeerpi4#46]
**Problem:** when a sensor is saved in the hardware config it spawns a new copy of its infinite async run() without killing the old one(s).

**reproduce:**

1. create a new CustomSensor / Dummy Sensor and save.
2. watch how it gets a new random value every second.
3. go into the edit menu of this sensor and save the sensor again (no changes needed)
4. watch how it gets a new random sensor value 2 times every second.
5. this effect stacks

**Additional information:** This seems to be true for every Sensor since it got my attention when developing my own sensor plugin.

**Comment by Prash3r** [comment]
Okay, i am a step further:

**Speculations:** The run() function loop should be `while self.running == True:` as it was some commits ago BUT the variable `self.running` should be set true in the base class's `__init__()` function. ALSO the base class `stop()` function should set `self.running` to false so the async loop kills all orphans of the old instance.

I think this applies for some more api classes and i can look into and implement it this this week, but please tell me if im missing something.

**Comment by Manuel83** [comment]
Pull Request merged
