### ISSUE TITLE
'Listening' to notification events from plugins

### ISSUE THREAD

**Issue by avollkopf** [Manuel83/craftbeerpi4#51]
@Manuel83  In CraftbeerPi3 it was possible to 'listen' to events. In this case, some plugins were using the message event to forward existing message content to other push services like 'pushover' or telgram.

The cbpi3 code is listed below:

```
@cbpi.event("MESSAGE", async=True)
def messageEvent(message, **kwargs):
    """
    React on message event. add the message to the cache and push the message to the clients
    :param message: the message
    :param kwargs: other parameter
    :return: None
    """
    if message["timeout"] is None:
        cbpi.cache["messages"].append(message)
    cbpi.emit("NOTIFY", message)
```
An example of the pushover code plugin from craftbeerpi3 that was using this. In the cbpi3 case message was the message itself and title the title of the message spcified in the cbpi3 notification function.

```
@cbpi.event("MESSAGE", async=True)
def messageEvent(message):
	pushoverData = {}
	pushoverData["token"] = pushover_token
	pushoverData["user"] = pushover_user
	pushoverData["message"] = message["message"]
	pushoverData["title"] = message["headline"]
	requests.post("https://api.pushover.net/1/messages.json", data=pushoverData)
```

Now we also have 'title' and 'message' with the new notification from cbpi 4.0.0.31. 

The question is, how to notice a notification from a plugin and access the title and message. Maybe it is already there but I don't see it. It would be great, if this would be working to support plugins for push notifications to other services.

**Comment by Manuel83** [comment]
I can add this feature quite easy. In CBPi 4 it will be always async.
Does that sounds good?

**Comment by avollkopf** [comment]
@Manuel83 That would be wonderful.

**Comment by avollkopf** [comment]
@Manuel83 Also an example on how to create a background task for a CBPiExtension Class would be great as it could be also helpful for the LCD Display plugin from @JamFfm. I am struggling already with adding config parameters for a potential pushover plugin as I need to somehow create a taks. However, if I create a taks via asyncio of a run() function, it looks good in the log but the web interface is not loading...

**Comment by avollkopf** [comment]
With the latest changes in cbpi (4.0.0.33) I was able to create a plugin that is listening to cbpi4 notifications and is forwarding them to the PushOver service.

https://pypi.org/project/cbpi4-PushOver/

https://github.com/avollkopf/cbpi4-PushOver

Issue can be closed
