### ISSUE TITLE
Any updates on this project?

### ISSUE THREAD

**Issue by gieljnssns** [Manuel83/craftbeerpi4#6]
As the title.....

**Comment by JonathanFager** [comment]
There has been no sign of Manuel working on Craftbeerpi 4 or 3 for at least a year, so nope...

**Comment by francoisduprez** [comment]
I saw some updates a few days back. Maybe there is hope..

**Comment by andlill** [comment]
[CraftBeerPi 4.0 Dashboard](https://www.youtube.com/watch?v=C9316yw54ts)

There is hope :)

**Comment by Manuel83** [comment]
Yes there is 🎉
