### ISSUE TITLE
Is there something simular to Backgroundtask?

### ISSUE THREAD

**Issue by JamFfm** [Manuel83/craftbeerpi4#62]
In CBPI 3 there is a possibility to user backgroundtasks. Is there anything simular in CBPI4?

**Comment by avollkopf** [comment]
Hi,

I think you ar elooking for something like this:

```
    def __init__(self,cbpi):
        self.cbpi = cbpi
        self._task = asyncio.create_task(self.run())

```

I am using this in my psuover plugin:

https://github.com/avollkopf/cbpi4-PushOver/blob/main/cbpi4-PushOver/__init__.py

**Comment by Manuel83** [comment]
Yes that the way to do

**Comment by JamFfm** [comment]
The task is only running once. 
I was trying to get the time on the LCD Display for testing purpose but it is only shown once.
No errors occure in the command log. 
In Cbpi3 there was an interval which could be selected.

This is the code I use. It should be close to the Notification  addin from avollkopf.
What am I doing wrong?

# -*- coding: utf-8 -*-
import time
import logging
import asyncio
from .RPLCD.i2c import CharLCD
from time import strftime
from cbpi.api import *
from cbpi.api.config import ConfigType


logger = logging.getLogger(__name__)
global lcd
lcd = CharLCD(i2c_expander='PCF8574', address=0x27, port=1, cols=20, rows=4, dotsize=8, charmap='A00', auto_linebreaks=True, backlight_enabled=True)


class LCDisplay(CBPiExtension):
    def __init__(self, cbpi):
        self.cbpi = cbpi
        self._task = asyncio.create_task(self.run())

    async def run(self):
        logger.info('Starting LCDisplay background task')
        'This is the main code'
        global lcd
        line1 = ((strftime(u"%Y-%m-%d %H:%M:%S", time.localtime())).ljust(20))
        # lcd._set_cursor_mode('hide')
        lcd.clear()
        lcd.cursor_pos = (2, 0)
        lcd.write_string(line1)


def setup(cbpi):
    cbpi.plugin.register("LCDisplay", LCDisplay)

**Comment by JamFfm** [comment]
Hi thanks, that's it. 

A backgroundtask would look like this:


```
# -*- coding: utf-8 -*-
import time
import logging
import asyncio
from .RPLCD.i2c import CharLCD
from time import strftime
from cbpi.api import *
from cbpi.api.config import ConfigType


logger = logging.getLogger(__name__)
lcd = CharLCD(i2c_expander='PCF8574', address=0x27, port=1, cols=20, rows=4, dotsize=8, charmap='A00', auto_linebreaks=True, backlight_enabled=True)


class LCDisplay(CBPiExtension):
    def __init__(self, cbpi):
        self.cbpi = cbpi
        self._task = asyncio.create_task(self.run())

    async def run(self):
        logger.info('Starting LCDisplay background task')
        'This is the main code'
        while True:
            global lcd
            line1 = ((strftime(u"%Y-%m-%d %H:%M:%S", time.localtime())).ljust(20))
            lcd._set_cursor_mode('hide')
            lcd.cursor_pos = (2, 0)
            lcd.write_string(line1)
        pass


def setup(cbpi):
    cbpi.plugin.register("LCDisplay", LCDisplay)

```
