### ISSUE TITLE
General question on steps like boil and mash or mashin

### ISSUE THREAD

**Issue by avollkopf** [Manuel83/craftbeerpi4#72]
@Manuel83 I have created a step plugin which also allows the step to switch the Kettle logic on and off when the steps starts/ends. This function can be configured via step properties. If wanted, I could add it to the native steps. 

If wanted, I could also add a MashIn step that is heating up to the MashIn temp, is sending a notification and waiting for the brewer to add the malt before moving on to the next step.

**Comment by hurra** [comment]
>If wanted, I could also add a MashIn step that is heating up to the MashIn temp, is sending a notification and waiting for the brewer to add the malt before moving on to the next step.

That sounds great!

**Comment by chr2002qw** [comment]
Would be a great feature like on V3.

**Comment by Manuel83** [comment]
Hi

Sounds nice! Would be perfect to have more steps types in the CBPi core. I can add them if you provide a pull request.

Where do I find the code example with the logic switch?

A general pattern in CBPi is that things are bundles in "controllers". 
All Controller are linked the CBPi Object. Most objects have reference to the cbpi object.

Example to switch the logic on and off

`await self.cbpi.kettle.toggle("")`

**Comment by avollkopf** [comment]
@Manuel83 I am using basically your code from the controller and the api to switch the kettly on or off (depending on the status). It could be probably even simplified but it is working without issues. My step collection can be found here:  https://github.com/avollkopf/cbpi4-BM_Steps. 

I can add some steps to the code via pull request.

Sligthly off topic:
I have also created a buzzer plugin. This is responing to notifications. Not sure if you are also planning to implement a native buzzer. If you want, you could also add this to cbpi directly. The buzzer plays different sounds depending on the type of the notification (info/success, warning or error). It is based on the listening function for notifications you implemented a few weeks ago.

**Comment by avollkopf** [comment]
@Manuel83 I am almost done. Will also add a Cooldown Step that Cools Down to a target temp and sends a notification once the target temp is reached. 

One thing I noticed is an error message raised by the sensor controller on steps that have not specified a sensor which is a NotificationStep in my case. I either missed it before 4.0.0.34 or it was not shown:
`
2021-04-20:07:38:08,121 ERROR    [sensor_controller.py:24] Faild read sensor value  'NoneType' object has no attribute 'instance'
`

This Error is also shown for the existing cbpi waitstep. It is not causing problems in the flow but might be confusing when you notice it first time.

I will create a pull request for the updated mashsteps later this week.
